UnReaL/Models/CreateViewModel.cs
using UnReaL.Repository;

namespace UnReaL.Models
{
    public class CreateViewModel
    {
        private readonly IURLValidationService _service = new URLValidationService();

        public ShortURL ShortURL { get; set; } = new ShortURL();
        public string ErrorString { get; set; } = string.Empty;

        public string ValidateInput(string input) => _service.ValidateInput(input);
    }
}

UnReaL/Models/ErrorViewModel.cs
namespace UnReaL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UnReaL/Models/ShortURL.cs
using System.ComponentModel.DataAnnotations;

namespace UnReaL.Models
{
    public class ShortURL
    {
        [Required]
        public int Id { get; set; } = 0;
        [Required]
        public string Url { get; set; } = string.Empty;
    }
}

UnReaL/Controllers/UnReaLController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UnReaL.Models;
using UnReaL.Repository;

namespace UnReaL.Controllers
{
    public class UnReaLController : Controller
    {
        private readonly IUnReaLService _appService;
        private readonly IBijectionService _bijectionService;

        private readonly CreateViewModel _createVM = new();

        public UnReaLController(IUnReaLService appService, IBijectionService bijectionService)
        {
            _appService = appService;
            _bijectionService = bijectionService;
        }

        public IActionResult Index() => RedirectToAction(actionName: nameof(Create));

        public IActionResult Create() => View(_createVM);

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ShortURL shortUrl)
        {
            _createVM.ShortURL = shortUrl;
            _createVM.ErrorString = _createVM.ValidateInput(shortUrl.Url);

            TryValidateModel(_createVM);
            if (ModelState.IsValid && string.IsNullOrEmpty(_createVM.ErrorString))
            {
                var savedItemId = _appService.Save(_createVM.ShortURL);

                return RedirectToAction(actionName: nameof(Show), routeValues: new { id = savedItemId });
            }

            return View(_createVM);
        }

        public IActionResult Show(int? id)
        {
            if (!id.HasValue) { return NotFound(); }

            var shortUrl = _appService.GetById(id.Value);
            if (shortUrl == null) { return NotFound(); }

            ViewData["Path"] = _bijectionService.Encode(shortUrl.Id);

            return View(shortUrl);
        }

        [HttpGet("/UnReaL/Go/{path:required}", Name = "UnReaL_Go")]
        public IActionResult Go(string path)
        {
            if (path == null) { return NotFound(); }

            var shortUrl = _appService.GetByPath(path);
            if (shortUrl == null) { return NotFound(); }

            return Redirect(shortUrl.Url);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() 
            => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

UnReaL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title style="font-size:xx-large">@ViewData["Title"] - UnReaL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UnReaL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark text-white">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="UnReaL" asp-action="Index">UnReaL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="UnReaL" asp-action="Create">Create New</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UnReaL/Views/UnReaL/Create.cshtml
@model CreateViewModel
@{
    ViewData["Title"] = "Create a new short URL";
}

<br />

<div class="jumbotron">

    <div class="text-light bg-dark w-50 rounded-3">
        <h1>UnReaL Shortener</h1>
    </div>

    <div class="text-light bg-dark w-50 rounded-3">
        <p>By entering in a URL in the text field below, we will create a short URL for you!</p>
    </div>
    <br />

    @if (!string.IsNullOrEmpty(Model.ErrorString))
    {
        <div class="bg-light w-auto rounded-3">
            <p style="color:darkred">@Model.ErrorString</p>
        </div>
        <br />
    }

    <form asp-action="Create">
        <div class="form-horizontal">
            <div class="input-group input-group-lg">
                <input asp-for="ShortURL.Url" class="form-control" placeholder="Paste the URL to be shorten..." />
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Shorten URL</button>
                </span>
            </div>
        </div>
    </form>
</div>

UnReaL/Views/UnReaL/Show.cshtml
@model ShortURL
@{
    ViewData["Title"] = "Details of a short URL";
}

<br />

<div class="jumbotron">

    <div class="text-light bg-dark w-50 rounded-3">
        <h1>UnReaL Shortener</h1>
    </div>

        <div class="text-light bg-dark w-50 rounded-3">
        <p>You can see below the details of this short URL.</p>
    </div>
    <br />

    <ul class="text-light bg-dark rounded-3 w-75" style="word-wrap:break-word">
        <li>
            <span class="col-md-2">
                <strong>URL Id:</strong>
            </span>
            @Model.Id
        </li>
        <li>
            <span class="col-md-2">
                <strong>Original URL:</strong>
            </span>
            <a href="@Model.Url">
                @Model.Url
            </a>
        </li>
        <li>
            <span class="col-md-2">
                <strong>Short URL:</strong>
            </span>
            <a asp-controller="UnReaL" asp-action="Go" asp-route-path="@ViewData["Path"]">
                http://localhost:5000/UnReaL/Go/@ViewData["Path"]
            </a>
        </li>
    </ul>
</div>